#how to run:
#mpirun -np 17 -hostfile hosts ./papers_computational_results 

CC=/usr/local/cuda-11.5/bin/nvcc
ARCH=-c -O3 -arch sm_75 -std=c++17
MPIINC=-I/home/user/Programs/openmpi/include -I/home/user/Programs/openmpi/include/openmpi -I/usr/local/cuda-11.3/targets/x86_64-linux/include
INCLUDE=$(MPIINC) -I./include -I./include/algorithms
MPILIB=-L/home/user/Programs/openmpi-4.1.3/ompi/.libs/lib -L/usr/local/cuda-11.3/targets/x86_64-linux/lib/
BASE=src/algorithms/*.cu  src/kernels/*.cu src/util.cu src/cryptanalysis_types.cu src/automatic_linear_expansions.cu src/crypt_dances_explorer.cu
OBJECTS = *.o

FLAGS=-lmpi -lopen-rte -lopen-pal -lnsl -l.util -lm


all: crypt_dances_explorer

crypt_dances_explorer : $(BASE)
	$(CC)  -O3 -arch sm_75 -std=c++17  $(INCLUDE) -lm -L$(MPILIB) $(FLAGS) -rdc=true $^ -o $@


%.o: %.cu
	$(CC) $(ARCH) $(INCLUDE) -lm -L$(MPILIB) $(FLAGS) -rdc=true $<


